version: '3.4'

services:
  magicdatabaseui:
    image: ${DOCKER_REGISTRY-}magicdatabaseui
    build:
      context: .
      dockerfile: MagicDatabase/Dockerfile
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=MagicCards;User=sa;Password=YourStrong!Passw0rd;
    networks:
      - magicnet

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/opt/mssql
    networks:
      - magicnet

networks:
  magicnet:
    driver: bridge

volumes:
  sqldata:
